# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc8118037859fbae1653e73ed50caa509c5857d26ad1a51d10a593934c1d1a0a17190171705bdde6748e11329bd0299a1b9f18f1a71b220ba7ffb7f626af85fa

test:
  secret_key_base: f5f25836de68fbc40de79064efa55db95b13d570d88345a5ba5ca6f767052668ff54ba0f140ed3299b27fbbfbb523629e82102995b48738f1c37ead0c03e6d8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
